#pragma once

#define RESOURCE_GDPR_CHECK	100
#define RESOURCE_CHALLENGE_TASK_REWARDS	101
#define RESOURCE_LOGIN_PARAM	102
#define RESOURCE_INFORMATIONLIST2	103
#define RESOURCE_ITEM_LIST	104
#define RESOURCE_MINING_RESOURCE	105
#define RESOURCE_AREA_LIST	106
