#pragma once

#define RESOURCE_DLL_LIBMYSQL	100
#define RESOURCE_DLL_LIBCRYPTO	101
#define RESOURCE_DLL_LIBSSL		102

#define RESOURCE_GDPR_CHECK					200
#define RESOURCE_CHALLENGE_TASK_REWARDS		201
#define RESOURCE_LOGIN_PARAM				202
#define RESOURCE_TPP_INFORMATIONLIST2		203
#define RESOURCE_ITEM_LIST					204
#define RESOURCE_MINING_RESOURCE			205
#define RESOURCE_AREA_LIST					206
#define RESOURCE_FOB_PARAM					207
#define RESOURCE_SECURITY_SETTINGS_PARAM	208
#define RESOURCE_FOB_DEPLOY_LIST			209
#define RESOURCE_STEAM_SHOP_ITEM_LIST		210
#define RESOURCE_MGO_PARAMETERS				211
#define RESOURCE_MGO_TITLE_LIST				212
#define RESOURCE_MGO_INFORMATIONLIST2		213
#define RESOURCE_MGO_RULE_STAT_LIST			214
#define RESOURCE_MGO_PURCHASABLE_LIST		215
#define RESOURCE_MGO_BASE_LOADOUTS			216
#define RESOURCE_MGO_BASE_AVATAR			217

#define RESOURCE_SQL_MYSQL					300
#define RESOURCE_SQL_SQLITE3				301
